Repository openshift/osd-operators-registry, pull requests merged in 2019-04, with the labels that each got.

#1 Merging original repo
  README.md
  manifests/01_dedicated-admin-operator.Subscription.yaml
  operators/dedicated-admin-operator/0.1.28-2019-03-27-8bbbc8f/dedicated-admin-operator.v0.1.28-2019-03-27-8bbbc8f.clusterserviceversion.yaml
  operators/dedicated-admin-operator/0.1.31-2019-03-29-3ff1db8/dedicated-admin-operator.v0.1.31-2019-03-29-3ff1db8.clusterserviceversion.yaml
  operators/dedicated-admin-operator/dedicated-admin-operator.package.yaml
  scripts/build_image_catalog.sh
  templates/template_osd-operators.CatalogSource.yaml
Labels: lgtm, size/L

#2 Generalizing build script
  .gitignore
  Dockerfile
  Makefile
  OWNERS
  README.md
  catalog-manifests/dedicated-admin-operator/0.1.28-2019-03-27-8bbbc8f/dedicated-admin-operator.v0.1.28-2019-03-27-8bbbc8f.clusterserviceversion.yaml
  catalog-manifests/dedicated-admin-operator/0.1.31-2019-03-29-3ff1db8/dedicated-admin-operator.v0.1.31-2019-03-29-3ff1db8.clusterserviceversion.yaml
  catalog-manifests/dedicated-admin-operator/dedicated-admin-operator.package.yaml
  checkout-operator.mk
  manifests/01_dedicated-admin-operator.Subscription.yaml
  operators/dedicated-admin-operator/dedicated-admin-operator.package.yaml
  project.mk
  scripts/build_image_catalog.sh
  scripts/gen_operator_csv.py
  scripts/templates/catalog.yaml
  scripts/templates/csv.yaml
  scripts/templates/operator.yaml
Labels: lgtm, size/XL

#3 Updates regarding releases and other fixes
  .gitignore
  Makefile
  README.md
  checkout-operator.mk
  manifests/00-catalog.yaml
  manifests/10-dedicated-admin-operator.yaml
  scripts/templates/operator.yaml
Labels: lgtm, size/L

#5 Check operator can be pulled before building catalog
  Makefile
  README.md
Labels: lgtm, size/S

#6 make git-commit adds manifests/
  Makefile
Labels: lgtm, size/XS

#9 CATALOG_VERSION is now CHANNEL-[md5sum of catalog-manifests contents]
  Makefile
  checkout-operator.mk
  functions.mk
  manifests/00-catalog.yaml
  manifests/10-dedicated-admin-operator.yaml
  project.mk
Labels: lgtm, size/M

#11 Push only the tag we created.
  Makefile
Labels: lgtm, size/XS

#16 Rename manifests copied to bundle
  scripts/gen_operator_csv.py
Labels: lgtm, size/XS

#12 Add support for multiple operators via several improvements
  Makefile
  README.md
  scripts/gen_operator_csv.py
Labels: kind/cleanup, kind/feature, lgtm, size/L

#17 SREP-1037 Generate SelectorSyncSet files
  Makefile
  manifests/hive/01-catalog.selectorsyncset.yaml
  manifests/hive/20-dedicated-admin-operator.selectorsyncset.yaml
  scripts/templates/catalog.selectorsyncset.yaml
  scripts/templates/operator.selectorsyncset.yaml
Labels: lgtm, size/L

#19 Add configure alertmanager operator
  Makefile
Labels: lgtm, size/XS

#24 Defer OperatorGroup creation requests to operators
  Makefile
  functions.mk
  scripts/templates/operator.yaml
  scripts/templates/operatorgroup.yaml
Labels: lgtm, size/M

#25 Allow operators to override MultiNamespace
  Makefile
  scripts/gen_operator_csv.py
Labels: lgtm, size/M
